export const turkishLabels = {
  firstName: "Ad",
  first_name: "Ad",
  lastName: "Soyad",
  last_name: "Soyad",
  tcKimlikNo: "TC Kimlik No",
  tc_kimlik_no: "TC Kimlik No",
  birthDate: "Doğum Tarihi",
  birth_date: "Doğum Tarihi",
  birthPlace: "Doğum Yeri",
  birth_place: "Doğum Yeri",
  maritalStatus: "Medeni Durum",
  marital_status: "Medeni Durum",
  motherName: "Anne Adı",
  mother_name: "Anne Adı",
  fatherName: "Baba Adı",
  father_name: "Baba Adı",
  email: "E-posta",
  phone: "Telefon",
  mobile: "Cep Telefonu",
  address: "Adres",
  city: "İl",
  district: "İlçe",
  postalCode: "Posta Kodu",
  postal_code: "Posta Kodu",
  companyName: "Şirket Adı",
  company_name: "Şirket Adı",
  companyActivity: "Faaliyet Alanı",
  company_activity: "Faaliyet Alanı",
  capital: "Sermaye",
  partnerCount: "Ortak Sayısı",
  partner_count: "Ortak Sayısı",
  workplaceAddress: "İşyeri Adresi",
  workplace_address: "İşyeri Adresi",
  workplaceCity: "İşyeri İl",
  workplace_city: "İşyeri İl",
  workplaceDistrict: "İşyeri İlçe",
  workplace_district: "İşyeri İlçe",
  workplaceType: "İşyeri Tipi",
  workplace_type: "İşyeri Tipi",
  name: "İsim",
  share: "Hisse Oranı (%)",
};

export const getLabelTR = (key) => {
  return turkishLabels[key] || key.replace(/_/g, " ").replace(/([A-Z])/g, " $1").trim();
};

